### ISSUE TITLE
sm.ms 上传图片 API 需要更新到 v2

### ISSUE THREAD

**Issue by dofy** [BlackwinMin/alfred-gallery#5]
文档 https://doc.sm.ms/

API 地址： POST https://sm.ms/api/v2/upload

另外，如果重复上传同一图片文件，返回数据存在差异，之前的正则字符串截取有问题，下列代码做了修复。 **（代码截取自以图搜图 File Action）**

```bash
# ...
var=$(curl -X POST -F smfile=@"$ARG" https://sm.ms/api/v2/upload | grep -o -E '"https:\\/\\/i\.loli\.net\\.*\.(png|jpg|jpeg)"' | sed 's/\\//g' | sed 's/"//g')
#...
```

**Comment by BlackwinMin** [comment]
感谢建议，已合并到相关动作（两个 Alfred、两个 LaunchBar）并注明 :D
