### ISSUE TITLE
OCR screenCapture 在 Big sur 中无法使用了

### ISSUE THREAD

**Issue by Chuck1sn** [BlackwinMin/alfred-gallery#7]
使用 ocr 截图后，无法自动识别转换为文字保存到剪贴板。

**Comment by BlackwinMin** [comment]
你好，我在 macOS 11.0.1 和 Alfred 4.2.1 下可以正常使用。可能的原因：
1. 未按说明安装 OCR 引擎
2. 未授权 Alfred 录制屏幕

**Comment by Chuck1sn** [comment]
你好。感谢回复。
我这边重新安装一下 ocr 引擎试试。

不过之前的 ocr 帖子实在找不到了，能再发一份吗给我吗，我想重新安装一次试试。
实在是非常感谢！

**Comment by BlackwinMin** [comment]
https://sspai.com/post/53321
这是付费内容的链接，根据合同我不能公开原文，故只能提供阅读链接

**Comment by Chuck1sn** [comment]
感谢。我就是付费用户。谢谢哈
另外请问下后期的打算是什么，是继续在别的平台写作还是自己开独立博客呀。

能不能通知下，我这边还挺喜欢看你的文章。

**Comment by BlackwinMin** [comment]
谢谢支持，文章还会写，近期可能就有新动作 :D
可以关注我的 Twitter Minja_Rin，新动态主要在 Twitter 宣布
