### ISSUE TITLE
Shell MacBook 问题

### ISSUE THREAD

**Issue by suliveevil** [BlackwinMin/alfred-gallery#8]
之前没有用过 Shell MacBook，第一次用发现图像大小失调了。
不记得自己之前调整过系统默认参数，2560x1600的屏幕，截图是2880x1800的：

<img width="377" alt="截屏2022-10-25 23 36 53" src="https://user-images.githubusercontent.com/35763237/197818830-970272cb-de9c-41f3-9e63-ffc84238c112.png">

![截屏2022-10-25 23 35 56_shelled](https://user-images.githubusercontent.com/35763237/197819235-fac09a01-e12e-44a7-bb63-0c7fa06e7f9e.png)

请问有什么办法在两张图片合成之前调整大小的方法吗？谢谢啦 🙏
目前在用 Mockview 但还是想有个第二方案。

**Comment by BlackwinMin** [comment]
试试在 `full_name=${f%.*}` 之前加上一行 `convert -resize 2560 "$f" "$f"`，调整一下分辨率。我已经不用 Alfred 了，没法直接帮你测试啦 QAQ

**Comment by suliveevil** [comment]
感谢感谢。
请问现在是只用KM了吗，还是换其他替代品了啊？

**Comment by BlackwinMin** [comment]
谈不上“现在”，因为 Alfred 我从来都没正经用过，只是在写 LaunchBar 脚本的时候顺手做一个 Alfred 版 😂
可以进群交流啊 https://utgd.net/member-community

**Comment by suliveevil** [comment]
Slack 有点难用啊🤣用Apple ID登陆自动生成的邮件地址没法加入工作区。
